language: c

branches:
  only:
    - escaping

dist: trusty
sudo: required

matrix:
  include:

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - FAVORITE_CONFIG=yes
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - config=release
        - CC1=gcc-6
        - CXX1=g++-6

rvm:
  - 2.2.3

install:
  - bash .travis_install.bash

script:
  - bash .travis_script.bash

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
    - kevincantu@gmail.com

deploy:
  - provider: bintray
    user: killerswan
    file: /home/travis/build/killerswan/ponyc/bintray_rpm.json
    on:
      branch: escaping
      condition: "$FAVORITE_CONFIG == yes"
    key:
      secure: "U8Klkg0uZRFR1A+8gVVmAhqGwlzbJcax8KIYQDHJv9qoV6oBtl01jyBjZTRG8FNVef7U6HKHGqJSoaY4ByGgPv79YlGFzpn2lZL550E0YFmpfYea6CPUqzkcVU/3FY30MlbYckUceZc4Eei68Ekm2CvN1bmktDz8r/NWHhAeMYAHIihLFulmlwm4zxDbTkHNtNW4rKjyCTAtbSP4yTyOCnQBo6wMor54IxJ/8al0fCy1IW4q3DdQaEjkUBmBigY1sya6tEhKr7IFoeabRZiiccYWv6T7LmSe72Nug6X2CWBrGLLk7+vANYfQy0O040fEWUFAuuc6G7mb5NTCcbE1BhH0VBpqxI7dkgnPpPVgogDqQ0y06PKfEJ69+8+F78DS/TLZTKrCL3nf7V5VLLUcRswSxJB2hAHwNtn1SH1pwY8zP5CUVlIVDVVObbpAB87shsKoWO/k4x8T6kWRKPy9IVO8kp5VaDJ4cBfew1COXbhQwRxiAzDnSzrarsGFJ7mM8wTv6nw0lxJg3p5eJND3U0JxKKz/D6wpEL7KtU2ltru8QXo7jzWB4mrv0K3uXFBhXLPOI83kwwhCdfLKqCL8m7rb1Ta3Ag3cO0AKmFj6ZIsX2dCN9k/W/DmOOxaWR+vkVQTxdaM9e2+QywmgPsiKyHx3Cd5e8Ao24/xict0tSGQ="
